version: "3.8"

services:
  backend:
    build:
      context: ./telegram-bot-service
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      USE_WEBHOOK: ${USE_WEBHOOK}
      WEBHOOK_URL: ${WEBHOOK_URL}
      BACKEND_URL: ${BACKEND_URL}
      INTERNAL_API_KEY: ${INTERNAL_API_KEY}
      AI_SERVICE_URL: http://ai-service:8001
    ports:
      - "8000:8000"
    depends_on:
      - ai-service

  ai-service:
    build:
      context: ./ai-service
    environment:
      A4F_API_KEY: ${A4F_API_KEY}
    ports:
      - "8001:8001"

  # frontend:
  #   build:
  #     context: ./front2
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     NEXT_PUBLIC_API_URL: http://backend:8000

