version: "3.8"

services:
  telegram-bot-service:
    build:
      context: ./telegram-bot-service
    environment:
      BOT_TOKEN: ${TELEGRAM__TOKEN}
      USE_WEBHOOK: ${USE_WEBHOOK}
      WEBHOOK_URL: ${WEBHOOK_URL}
      BACKEND_URL: ${BACKEND_URL}
      INTERNAL_API_KEY: ${INTERNAL_API_KEY}
      AI_SERVICE_URL: http://localhost:8001
    ports:
      - "8000:8000"
    volumes:
      - logs:/app/logs
    depends_on:
      - ai-service

  ai-service:
    build:
      context: ./ai-service
    environment:
      A4F_API_KEY: ${A4F_API_KEY}
    ports:
      - "8001:8001"
    volumes:
      - logs:/app/logs

volumes:
  logs:
